services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    environment:
      - ./.env
    command: npm run start:dev